### ISSUE TITLE
npm是真的挂了

### ISSUE THREAD

**Issue by RoseEnd** [HcySunYang/scroll-flip-page#2]
npm是真的挂了

**Comment by HcySunYang** [comment]
贴出报错信息

**Comment by RoseEnd** [comment]
![1](https://user-images.githubusercontent.com/19225061/35260506-f4ce03fe-0046-11e8-9efd-b4c32102b404.png)

**Comment by HcySunYang** [comment]
单词拼写错误，是 flip 不是 filp

**Comment by RoseEnd** [comment]
复制文档上的，结果错了，你记得改一下哦

**Comment by HcySunYang** [comment]
好的，感谢提醒
