### ISSUE TITLE
为什么不加上一个横向滚动的组件呢？

### ISSUE THREAD

**Issue by lbhsot** [HcySunYang/scroll-flip-page#4]
或者能分享一下怎么将这个simulation-scroll-y组件封装成Vue的component的吗？

**Comment by HcySunYang** [comment]
额。。。这是什么问题？这个问题已经上升到如何编写一个Vue组件了，比如你觉得moment这个库用来处理日期时间的操作非常方便，你想封装一个Vue组件，可以啊；比如你觉得popmotion这个库用来做动画效果很方便，你想封装一个Vue组件可以啊；再比如你想把finger-mover封装成Vue组件也是可以的。但是这些库都不会告诉你应该怎么去封装。因为这是不在他们负责的领域之内。工具都给你写好了，你想怎么用就怎么用，无论你拿去用在Vue中还是React中甚至JQuery中。
